name: Build & push to testing

on:
  workflow_dispatch

env:
  CARGO_TERM_COLOR: always
  CLICOLOR: 1

jobs:
  do-test-build:
    name: Do test build
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        rust: ["stable"]
    continue-on-error: ${{ matrix.rust != 'stable' }}
    runs-on: self-hosted

    steps:
      - name: Init Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install Zola
        uses: taiki-e/install-action@v2
        with:
          tool: zola

      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Say hi
        run: |
          echo "HI!"
